---
- hosts: all
  user: vagrant
  sudo: yes  
  gather_facts: yes
  roles:
    - common  

## This role deploys shipyard-agents
- hosts: shipyard-agents  
  user: vagrant
  sudo: yes  
  roles:    
    - docker-host
    - shipyard-agent
      
## This role deploys a docker registry
- hosts: docker-registry-servers
  user: vagrant
  sudo: yes
  roles:
    - docker-host
    - docker-registry
    - webserver-vhost
 
# This role deploys a shipyard server
- hosts: shipyard-servers
  user: vagrant
  sudo: yes    
  roles:
    - docker-host
    - shipyard-www
    - webserver-vhost    

# This role deploys a rabbitmq server
- hosts: rabbitmq-servers
  user: vagrant
  sudo: yes    
  roles:
    - rabbitmq
    