---
- hosts: all
  user: vagrant
  sudo: yes  
  gather_facts: yes
  roles:
    - common  
    - docker-host
  
## This playbook deploys a docker registry
- hosts: docker-registry-servers
  roles:
    - docker-registry
 
# This playbook deploys a shipyard server

- hosts: shipyard-servers
  user: vagrant
  sudo: yes    
  roles:    
    - shipyard-base
    - shipyard-redis
    - shipyard-router
    - shipyard-lb
    - shipyard-db
    - shipyard-www
    
- hosts: shipyard-agents  
  user: vagrant
  sudo: yes  
  roles:    
    - shipyard-agent