---
- hosts: all
  user: vagrant
  sudo: yes  
  gather_facts: yes
  roles:
    - common  
    - docker-host

## This role deploys shipyard-agents
- hosts: shipyard-agents  
  user: vagrant
  sudo: yes  
#  roles:    
#    - shipyard-agent
      
## This role deploys a docker registry
- hosts: docker-registry-servers
  user: vagrant
  sudo: yes
  roles:
    - docker-registry
    - webserver-vhost
    - shipyard-agent
 
# This role deploys a shipyard server
- hosts: shipyard-servers
  user: vagrant
  sudo: yes    
  roles:
    - shipyard-www
    - webserver-vhost    
    