---
-   name: Include common variables.
    include_vars: common
    
-   name: Include OS-specific variables.
    include_vars: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}"

-   include: "setup_Debian.yml"
    when: ansible_os_family == 'Debian'
      
-   name: restart-docker
    service: name={{ docker_service }} state=restarted
    when: docker_ext_action.changed            
  
-   name: wait for docker on private ip port 4243
    wait_for: port=4243 delay=15 host={{ ansible_default_ipv4.address }}
    when: docker_ext_action.changed    

-   debug: msg="docker is up and listening on port 4243"
    when: docker_ext_action.changed