# {{ ansible_managed }}
# DESCRIPTION:    Image with Shipyard Server
# TO_BUILD:       docker build -rm -t shipyard_server/deploy

from stackbrew/ubuntu:12.04
maintainer Soumen Trivedi "https://github.com/soumentrivedi"
{% if http_proxy is defined %}
	env http_proxy {{ http_proxy }}
{% endif %}

{% if https_proxy is defined %}
	env https_proxy {{ https_proxy }}
{% endif %}

run apt-get update
run apt-get install -y python-dev python-setuptools libxml2-dev libxslt-dev libmysqlclient-dev supervisor wget make g++ libreadline-dev libncurses5-dev libpcre3-dev libpq-dev libmysqlclient-dev git-core
env SHIPYARD_APP_DIR /app
run easy_install pip
run pip install setuptools --no-use-wheel --upgrade
run pip install uwsgi==2.0.2
run pip install MySQL-Python==1.2.3
run pip install psycopg2
add . $SHIPYARD_APP_DIR
add .docker/known_hosts /root/.ssh/known_hosts
run (find $SHIPYARD_APP_DIR -name "*.db" -delete)
run pip install --upgrade -r $SHIPYARD_APP_DIR/requirements.txt
run (cd $SHIPYARD_APP_DIR && python manage.py syncdb --noinput)
run (cd $SHIPYARD_APP_DIR && python manage.py migrate)
run (cd $SHIPYARD_APP_DIR && python manage.py update_admin_user --username=admin --password=shipyard)

volume /var/log/shipyard
expose 8000
{% if enable_ssh %}
	expose 22
{% endif %}

workdir /app
cmd ["/app/.docker/run.sh"]