---
galaxy_info:
  author: Soumen Trivedi
  description: Ansible Role to setup shipyard postgresql database on Ubuntu 12.04 or above
  min_ansible_version: 1.7
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
  categories:
    - development
    - packaging
    - system
dependencies:
    - { role: shipyard-lb }
  # List your role dependencies here, one per line. Only
  # dependencies available via galaxy should be listed here.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.