# {{ ansible_managed }}
# DESCRIPTION:    Image with docker-registry project and dependencies
# TO_BUILD:       docker build -rm -t registry .
# TO_RUN:         docker run -p 5000:5000 registry

# Latest Ubuntu LTS
from    ubuntu:14.04

{% if http_proxy is defined %}
	env http_proxy {{ http_proxy }}
{% endif %}

{% if https_proxy is defined %}
	env https_proxy {{ https_proxy }}
{% endif %}

{% if no_proxy is defined %}
	env no_proxy {{ no_proxy }}
{% endif %}

# Update
run apt-get update
run apt-get -y upgrade

# Install pip
run apt-get -y install python-pip

# Install deps for backports.lzma (python2 requires it)
run apt-get -y install python-dev liblzma-dev libevent1-dev

add . /docker-registry
add ./config/boto.cfg /etc/boto.cfg

# Install core
run pip install /docker-registry/depends/docker-registry-core

# Install registry
run pip install file:///docker-registry#egg=docker-registry[bugsnag,newrelic]

env DOCKER_REGISTRY_CONFIG /docker-registry/config/config.yml
env SETTINGS_FLAVOR {{ registry_settings_mode }}
env GUNICORN_ACCESS_LOG_FILE {{ registry_access_log }}
env GUNICORN_ERROR_LOG_FILE {{ registry_error_log }}

expose {{ docker_registry_port }}

{% if enable_ssh %}
	expose 22
{% endif %}

workdir /docker-registry
cmd gunicorn -c gunicorn-config.py {{ registry_application_name }}
