---
-   name: Run the equivalent of "apt-get update" as a separate step
    apt: update_cache=yes

-   name: setting up base platform for hosting docker containers
    apt: name={{ item }} state=installed
    when: ansible_distribution == 'Ubuntu'
    with_items:    
    - "{{ubuntu_packages}}"
    - "{{common_packages}}" 

-   name: Updating kernel packages
    apt: name={{ item }} state=installed
    when: ansible_distribution == 'Ubuntu'
    with_items:    
    - "{{kernel_packages}}"
    register: kernelup

-   name: Restart the server
    command: /sbin/reboot
    sudo: true
    when: kernelup.changed

-   name: Wait for server to come up
    local_action: wait_for host={{ansible_ssh_host}} port={{ansible_ssh_port}} delay={{ restart_delay }}
    sudo: false    
    when: kernelup.changed

-   name: installing pip modules
    pip: name={{ item }} state=present
    when: ansible_distribution == 'Ubuntu'
    environment: 
      http_proxy: "{{ http_proxy }}"
      https_proxy: "{{ http_proxy }}"
      no_proxy: "{{ no_proxy }}" 
    with_items:    
    - "{{ docker_pips }}"
    when: https_proxy is not defined

-   name: installing pip modules
    pip: name={{ item }} state=present
    when: ansible_distribution == 'Ubuntu'
    environment: 
      http_proxy: "{{ http_proxy }}"
      https_proxy: "{{ https_proxy }}"
      no_proxy: "{{ no_proxy }}" 
    with_items:    
    - "{{ docker_pips }}"
    when: https_proxy is defined
-   name: Run the equivalent of "apt-get update" as a separate step
    apt: update_cache=yes
            