---
-   name: Include OS-specific variables.
    include_vars: "{{ ansible_os_family }}"
    
-   include: "setup_Debian.yml"
    when: ansible_os_family == 'Debian'

-   name: Enable Apache mods
    apache2_module: >
      name={{ item }}      
      state=present
    with_items: apache_mods_enabled
    notify: restart apache
      
-   name: Add apache vhosts configuration.
    template: >
      src=vhosts.conf.j2
      dest={{ apache_conf_path }}/{{ base_service }}.conf
      owner=root group=root mode=644
    notify: restart apache
    when: apache_create_vhosts

-   name: Ensure Apache is started and enabled on boot.
    service: >
      name={{ apache_daemon }}
      state=started
      enabled=yes