---
-   name: Ensure Apache is installed (Debian).
    apt: >
      name={{ item }}
      state=installed
    with_items: apache_packages

-   name: Configure Apache (Debian).
    lineinfile: >
      dest="{{ apache_server_root }}/ports.conf"
      regexp="{{ item.regexp }}"
      line="{{ item.line }}"
      state=present
    with_items:
    - {
        regexp: "^Listen ",
        line: "Listen {{ apache_listen_port }}"
      }
    - {
        regexp: "^NameVirtualHost ",
        line: "NameVirtualHost *:{{ apache_listen_port }}"
      }
    notify: restart apache
    
-   name: Disable Apache sites
    command: >
      {{ apache_disable_site_daemon }} {{ item }} 
      creates={{ apache_server_root }}/sites-available/{{ item }}.disable     
    with_items: apache_sites_disabled
    notify: restart apache        