---
galaxy_info:
  author: Soumen Trivedi
  description: Ansible Role to setup webserver and vhosts
  min_ansible_version: 1.7
  platforms:
    - name: Ubuntu
      versions:
        - all
  categories:
    - web
dependencies: []
  # List your role dependencies here, one per line. Only
  # dependencies available via galaxy should be listed here.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.